// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"yellowbook/internal/repository"
	"yellowbook/internal/repository/cache"
	"yellowbook/internal/repository/cache/ristretto"
	"yellowbook/internal/repository/dao"
	"yellowbook/internal/service"
	"yellowbook/internal/web"
	"yellowbook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	db := ioc.InitDB()
	userDAO := dao.NewUserDAO(db)
	cmdable := ioc.InitRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDAO, userCache)
	iUserService := service.NewUserService(userRepository)
	ristrettoCache := ioc.InitRistretto()
	codeCache := ristretto.NewCodeCache(ristrettoCache)
	codeRepository := repository.NewCodeRepository(codeCache)
	client := ioc.InitCloopen()
	smsService := ioc.InitSMSService(client)
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(iUserService, codeService)
	engine := ioc.InitWebServer(userHandler)
	return engine
}
