// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"yellowbook/internal/repository"
	"yellowbook/internal/repository/cache"
	"yellowbook/internal/repository/dao"
	"yellowbook/internal/service"
	"yellowbook/internal/service/sms/cloopen"
	"yellowbook/internal/web"
)

// Injectors from wire.go:

func InitUserHandler(smsAppId string) *web.UserHandler {
	db := initDB()
	userDAO := dao.NewUserDAO(db)
	cmdable := initRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	client := initCloopen()
	smsService := cloopen.NewService(client, smsAppId)
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService)
	return userHandler
}
