apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yellowbook-mysql-claim
  namespace: ingress-nginx
spec:
  storageClassName: suibian
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  