apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
  namespace: ingress-nginx
spec:
  storageClassName: suibian
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/live"
  